package persons_engine

// ptr returns a pointer to s. Used to set SupportGuideID in seed data.
func ptr(s string) *string { return &s }

// seedPersons loads 19 plausible Melbourne persons into r.
// Persons are spread across 11 suburbs with 7 distinct needs types.
// All SupportGuideID values correspond to valid knowledge-engine article IDs.
func seedPersons(r *MockPersonRepository) {
	persons := []Person{
		// --- CBD (3) ---
		{
			ID:             "per-001",
			Label:          "Margaret W. — CBD",
			Address:        "210 Lonsdale St, Melbourne VIC",
			Needs:          []string{"mobility"},
			NeedsSummary:   "Uses a manual wheelchair; requires evacuation chair or two-person carry on stairs.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-017"),
			Lat:            -37.8120,
			Lng:            144.9630,
			Destination:    PersonDestination{Lat: -37.7987, Lng: 144.9553, Label: "Royal Melbourne Hospital"},
		},
		{
			ID:             "per-002",
			Label:          "David K. — CBD",
			Address:        "45 Bourke St, Melbourne VIC",
			Needs:          []string{"hearing"},
			NeedsSummary:   "Profoundly deaf; relies on visual alerts, written instructions, and sign language interpretation.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-013"),
			Lat:            -37.8140,
			Lng:            144.9650,
			Destination:    PersonDestination{Lat: -37.8248, Lng: 144.9537, Label: "Melbourne Convention Centre"},
		},
		{
			ID:             "per-003",
			Label:          "Susan T. — CBD",
			Address:        "188 La Trobe St, Melbourne VIC",
			Needs:          []string{"cognitive"},
			NeedsSummary:   "Intellectual disability; needs clear step-by-step spoken instructions and a familiar support worker present.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-009"),
			Lat:            -37.8100,
			Lng:            144.9610,
			Destination:    PersonDestination{Lat: -37.7987, Lng: 144.9553, Label: "Royal Melbourne Hospital"},
		},
		// --- Carlton (2) ---
		{
			ID:             "per-004",
			Label:          "James R. — Carlton",
			Address:        "118 Lygon St, Carlton VIC",
			Needs:          []string{"autism"},
			NeedsSummary:   "Autistic adult; sensory overload risk in crowds — needs quiet space, predictable routine, and advance warning of sirens.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-006"),
			Lat:            -37.8002,
			Lng:            144.9674,
			Destination:    PersonDestination{Lat: -37.8052, Lng: 144.9719, Label: "Carlton Gardens Emergency Assembly"},
		},
		{
			ID:             "per-005",
			Label:          "Emily C. — Carlton",
			Address:        "72 Drummond St, Carlton VIC",
			Needs:          []string{"cognitive"},
			NeedsSummary:   "Developmental delay; needs a familiar caregiver or support person to accompany during evacuation.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-011"),
			Lat:            -37.7995,
			Lng:            144.9680,
			Destination:    PersonDestination{Lat: -37.8052, Lng: 144.9719, Label: "Carlton Gardens Emergency Assembly"},
		},
		// --- Docklands (2) ---
		{
			ID:             "per-006",
			Label:          "Robert M. — Docklands",
			Address:        "28 Harbour Esplanade, Docklands VIC",
			Needs:          []string{"mobility"},
			NeedsSummary:   "Power wheelchair user; requires lift-accessible evacuation route — cannot use stairs under any circumstances.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-031"),
			Lat:            -37.8148,
			Lng:            144.9400,
			Destination:    PersonDestination{Lat: -37.8248, Lng: 144.9537, Label: "Melbourne Convention Centre"},
		},
		{
			ID:             "per-007",
			Label:          "Linda H. — Docklands",
			Address:        "60 NewQuay Promenade, Docklands VIC",
			Needs:          []string{"hearing"},
			NeedsSummary:   "Hard of hearing; relies on lipreading and vibrating phone alerts — cannot hear verbal announcements or sirens.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-014"),
			Lat:            -37.8155,
			Lng:            144.9420,
			Destination:    PersonDestination{Lat: -37.8248, Lng: 144.9537, Label: "Melbourne Convention Centre"},
		},
		// --- Richmond (2) ---
		{
			ID:             "per-008",
			Label:          "Liam P. — Richmond",
			Address:        "245 Bridge Rd, Richmond VIC",
			Needs:          []string{"autism"},
			NeedsSummary:   "Child with autism; needs trauma-informed, calm first-responder approach — avoid sudden loud commands.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-008"),
			Lat:            -37.8181,
			Lng:            144.9990,
			Destination:    PersonDestination{Lat: -37.8167, Lng: 144.9839, Label: "Yarra Park Emergency Assembly"},
		},
		{
			ID:             "per-009",
			Label:          "Patricia N. — Richmond",
			Address:        "92 Swan St, Richmond VIC",
			Needs:          []string{"mobility"},
			NeedsSummary:   "Spinal cord injury — do not move without trained personnel; risk of further injury if carry technique is incorrect.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-017"),
			Lat:            -37.8200,
			Lng:            144.9980,
			Destination:    PersonDestination{Lat: -37.8459, Lng: 144.9850, Label: "Alfred Hospital"},
		},
		// --- South Yarra (2) ---
		{
			ID:             "per-010",
			Label:          "Michael B. — South Yarra",
			Address:        "350 Toorak Rd, South Yarra VIC",
			Needs:          []string{"cognitive"},
			NeedsSummary:   "Psychosocial disability; requires mental health crisis plan and de-escalation before physical assistance.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-020"),
			Lat:            -37.8390,
			Lng:            144.9920,
			Destination:    PersonDestination{Lat: -37.8459, Lng: 144.9850, Label: "Alfred Hospital"},
		},
		{
			ID:             "per-011",
			Label:          "Helen G. — South Yarra",
			Address:        "48 Chapel St, South Yarra VIC",
			Needs:          []string{"visual-impairment"},
			NeedsSummary:   "Blind; needs sighted guide assistance and route familiarisation — familiar routes may be disrupted by debris.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-015"),
			Lat:            -37.8400,
			Lng:            144.9930,
			Destination:    PersonDestination{Lat: -37.8459, Lng: 144.9850, Label: "Alfred Hospital"},
		},
		// --- Fitzroy (2) ---
		{
			ID:             "per-012",
			Label:          "Karen L. — Fitzroy",
			Address:        "295 Brunswick St, Fitzroy VIC",
			Needs:          []string{"hearing"},
			NeedsSummary:   "Uses AAC device for communication; needs battery backup and communication board during evacuation.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-022"),
			Lat:            -37.7985,
			Lng:            144.9782,
			Destination:    PersonDestination{Lat: -37.8052, Lng: 144.9719, Label: "Carlton Gardens Emergency Assembly"},
		},
		{
			ID:             "per-013",
			Label:          "Noah F. — Fitzroy",
			Address:        "110 Smith St, Fitzroy VIC",
			Needs:          []string{"autism"},
			NeedsSummary:   "Autistic teenager with sensory kit; needs predictable instructions and advance warning before environment changes.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-007"),
			Lat:            -37.7995,
			Lng:            144.9790,
			Destination:    PersonDestination{Lat: -37.8052, Lng: 144.9719, Label: "Carlton Gardens Emergency Assembly"},
		},
		// --- Northcote (1) ---
		{
			ID:             "per-014",
			Label:          "Brian A. — Northcote",
			Address:        "185 High St, Northcote VIC",
			Needs:          []string{"cognitive"},
			NeedsSummary:   "Acquired brain injury; caregiver backup plan required — primary carer may also be affected in a widespread disaster.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-018"),
			Lat:            -37.7732,
			Lng:            144.9970,
			Destination:    PersonDestination{Lat: -37.7987, Lng: 144.9553, Label: "Royal Melbourne Hospital"},
		},
		// --- Clayton / Monash area (5) ---
		{
			ID:             "per-015",
			Label:          "Eleanor S. — Clayton",
			Address:        "15 Ancora Imparo Way, Clayton VIC",
			Needs:          []string{"mobility", "elderly"},
			NeedsSummary:   "Frail 78-year-old; uses a four-wheel walker and cannot manage stairs or long unassisted walks — needs slow pace and rest stops.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-017"),
			Lat:            -37.9105,
			Lng:            145.1340,
			Destination:    PersonDestination{Lat: -37.9140, Lng: 145.1330, Label: "Monash University Campus Assembly Point"},
		},
		{
			ID:             "per-016",
			Label:          "Thomas D. — Clayton",
			Address:        "42 Clayton Rd, Clayton VIC",
			Needs:          []string{"hearing", "communication"},
			NeedsSummary:   "Profoundly deaf and non-verbal; communicates via Auslan and written notes — bring a pen-and-paper or text-capable device.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-022"),
			Lat:            -37.9230,
			Lng:            145.1210,
			Destination:    PersonDestination{Lat: -37.9210, Lng: 145.1195, Label: "Clayton Recreation Reserve"},
		},
		{
			ID:             "per-017",
			Label:          "Margaret O. — Oakleigh",
			Address:        "78 Princes Hwy, Oakleigh VIC",
			Needs:          []string{"cognitive", "elderly"},
			NeedsSummary:   "82-year-old with mild dementia; disoriented under stress — give short, repeated instructions and stay within sight at all times.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-018"),
			Lat:            -37.9000,
			Lng:            145.0910,
			Destination:    PersonDestination{Lat: -37.8993, Lng: 145.0929, Label: "Oakleigh Emergency Assembly Point"},
		},
		{
			ID:             "per-018",
			Label:          "Henry M. — Mulgrave",
			Address:        "5 Springvale Rd, Mulgrave VIC",
			Needs:          []string{"mobility"},
			NeedsSummary:   "Below-knee amputee; uses prosthesis and a single crutch — limited stamina on uneven ground, may need transport over longer distances.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-031"),
			Lat:            -37.9270,
			Lng:            145.1660,
			Destination:    PersonDestination{Lat: -37.9278, Lng: 145.1648, Label: "Waverley Park Assembly Point"},
		},
		{
			ID:             "per-019",
			Label:          "Beatrice V. — Dingley Village",
			Address:        "120 Centre Dandenong Rd, Dingley Village VIC",
			Needs:          []string{"hearing", "elderly"},
			NeedsSummary:   "75-year-old with severe hearing loss; relies on hearing aids and lipreading — face her directly when speaking and avoid masks where possible.",
			CtaLabel:       "Navigate here",
			SupportGuideID: ptr("resource-014"),
			Lat:            -37.9790,
			Lng:            145.1220,
			Destination:    PersonDestination{Lat: -37.9780, Lng: 145.1210, Label: "Dingley Village Community Centre"},
		},
	}

	for _, p := range persons {
		r.upsert(p)
	}
}
